import io
from datetime import UTC, datetime

from reportlab.lib import colors
from reportlab.lib.pagesizes import letter
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle

from app.models.scan import Scan

def generate_pdf_report(scan: Scan) -> bytes:
    buffer = io.BytesIO()
    doc = SimpleDocTemplate(
        buffer,
        pagesize=letter,
        rightMargin=72,
        leftMargin=72,
        topMargin=72,
        bottomMargin=18
    )
    
    styles = getSampleStyleSheet()
    title_style = styles['Heading1']
    h2_style = styles['Heading2']
    normal_style = styles['Normal']
    
    Story = []
    
    # Title
    Story.append(Paragraph(f"AegisSec Vulnerability Assessment", title_style))
    Story.append(Spacer(1, 12))
    
    # Executive Summary
    Story.append(Paragraph("Executive Summary", h2_style))
    target_val = scan.target.value if scan.target else "Unknown Target"
    Story.append(Paragraph(f"Assessment for <b>{target_val}</b> ({scan.name}) completed with an overall risk score of <b>{scan.risk_score}/100</b>.", normal_style))
    Story.append(Spacer(1, 12))
    
    # Findings Summary Table
    Story.append(Paragraph("Findings Summary", h2_style))
    if scan.findings:
        data = [['Severity', 'Title', 'CVSS']]
        for finding in scan.findings:
            data.append([finding.severity.upper(), finding.title, str(finding.cvss)])
            
        t = Table(data, colWidths=[80, 300, 50])
        t.setStyle(TableStyle([
            ('BACKGROUND', (0,0), (-1,0), colors.grey),
            ('TEXTCOLOR', (0,0), (-1,0), colors.whitesmoke),
            ('ALIGN', (0,0), (-1,-1), 'LEFT'),
            ('FONTNAME', (0,0), (-1,0), 'Helvetica-Bold'),
            ('BOTTOMPADDING', (0,0), (-1,0), 12),
            ('BACKGROUND', (0,1), (-1,-1), colors.beige),
            ('GRID', (0,0), (-1,-1), 1, colors.black),
        ]))
        Story.append(t)
    else:
        Story.append(Paragraph("No vulnerabilities discovered.", normal_style))
        
    Story.append(Spacer(1, 24))
    
    # Detailed Findings
    Story.append(Paragraph("Technical Details", h2_style))
    for finding in scan.findings:
        Story.append(Paragraph(f"<b>{finding.title}</b> ({finding.severity.upper()})", styles['Heading3']))
        Story.append(Paragraph(f"<b>Description:</b> {finding.description}", normal_style))
        Story.append(Spacer(1, 6))
        Story.append(Paragraph(f"<b>Recommendation:</b> {finding.recommendation}", normal_style))
        Story.append(Spacer(1, 12))
        
    # Appendix
    Story.append(Spacer(1, 24))
    Story.append(Paragraph("Appendix", h2_style))
    Story.append(Paragraph(f"Generated by AegisSec AI Platform on {datetime.now(UTC).strftime('%Y-%m-%d %H:%M:%S UTC')}. Authorized use only.", normal_style))
    
    doc.build(Story)
    pdf = buffer.getvalue()
    buffer.close()
    return pdf
