import json
from datetime import UTC, datetime
from app.models.scan import Scan

def build_json_report(scan: Scan) -> str:
    payload = {
        "metadata": {
            "target": scan.target.value if scan.target else "Unknown",
            "scan_id": scan.id,
            "generated_at": datetime.now(UTC).isoformat()
        },
        "executive_summary": f"Assessment for {scan.name} completed with risk score {scan.risk_score}.",
        "risk_rating": scan.risk_score,
        "finding_summary": [
            {
                "title": finding.title, 
                "severity": finding.severity, 
                "cvss": finding.cvss,
                "remediation_priority": finding.remediation_priority
            }
            for finding in scan.findings
        ],
        "technical_details": [
            {
                "title": finding.title,
                "description": finding.description,
                "evidence": finding.evidence,
                "recommendation": finding.recommendation,
                "mappings": {
                    "owasp": finding.owasp,
                    "mitre_attack": finding.mitre_attack,
                    "cwe": finding.cwe
                }
            }
            for finding in scan.findings
        ],
        "appendix": {"platform": "AegisSec Enterprise", "authorized_use_only": True},
    }
    return json.dumps(payload, indent=2)


def build_html_report(scan: Scan) -> str:
    findings = "".join(
        f"""
        <li>
            <strong>{finding.title} ({finding.severity.upper()})</strong><br/>
            <em>CVSS 3.1:</em> {finding.cvss} | <em>Priority:</em> {finding.remediation_priority}<br/>
            <em>Mappings:</em> {finding.owasp or "N/A"} / {finding.mitre_attack or "N/A"} / {finding.cwe or "N/A"}<br/>
            <p><strong>Description:</strong> {finding.description}</p>
            <p><strong>Evidence:</strong> <pre>{finding.evidence or "N/A"}</pre></p>
            <p><strong>Recommendation:</strong> {finding.recommendation}</p>
        </li>
        <hr/>
        """
        for finding in scan.findings
    )
    
    target_val = scan.target.value if scan.target else "Unknown"
    
    return (
        "<html><body style='font-family: sans-serif; max-width: 800px; margin: auto;'>"
        f"<h1 style='color: #1e3a8a;'>AegisSec Enterprise Report: {scan.name}</h1>"
        f"<h2>Executive Summary</h2>"
        f"<p>Target: <strong>{target_val}</strong></p>"
        f"<p>Overall Risk Score: <strong>{scan.risk_score}/100</strong></p>"
        f"<h2>Detailed Technical Findings</h2><ul>{findings}</ul>"
        "<h2>Appendix</h2><p>Generated by AegisSec AI Platform. Authorized use only.</p>"
        "</body></html>"
    )

